import type { Metadata } from 'next';
import './globals.css';
import Header from './base/Header';
import Footer from './base/Footer';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
    title: 'WeatherNow',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={` font-montserrat  antialiased flex flex-col justify-between  min-h-[100vh]`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header />
                    {children}

                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
